### ISSUE TITLE
Could you move to JCenter?

### ISSUE THREAD

**Issue by yolapop** [xgc1986/ParallaxPagerTransformer#3]
New Android Studio by default is using JCenter repository, so it will be great if you can add there too..

**Comment by xgc1986** [comment]
I have just moved to jcenter, I didn't know about jcenter repository. Thanks :)

**Comment by yolapop** [comment]
Hi, have you checked it? There's no file there. Android Studio couldn't find it.

**Comment by xgc1986** [comment]
that's weird. I will check again

**Comment by xgc1986** [comment]
did you try to add manually into your build gradle

```dependencies {
   //...
    compile 'com.xgc1986.parallaxPagerTransformer:library:1.0.0:release@aar'
}```

(or the same in the README.md file?

it's working for me

**Comment by yolapop** [comment]
I know why it didn't work.. take a look at project's `build.gradle` and you'll find that you're still using mavenCentral().

It should be like this on every default android project:

    // Top-level build file where you can add configuration options common to all sub-projects/modules.

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.0.0'

            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }

    allprojects {
        repositories {
            jcenter()
        }
    }

**Comment by xgc1986** [comment]
I'm not using mavencentral, I just checked and it's jcenter
library: https://github.com/xgc1986/ParallaxPagerTransformer/blob/master/ParallaxPagerTransformer/build.gradle

sample: https://github.com/xgc1986/ParallaxPagerTransformer/blob/master/ParallaxProjectSample/build.gradle

and the sample is working for me :S

**Comment by yolapop** [comment]
I just cloned your sample and imported them to Android Studio and voila, it didn't work.. I don't know what's wrong though... I did try to change `jcenter()` to `mavenCentral()` and it worked, hence my comment above.

So i guess i'll download the aar and add it manually for temporary solution.

![gradle](https://cloud.githubusercontent.com/assets/2100294/6393742/5f302ebc-bdff-11e4-8561-b3a499976c56.png)

**Comment by xgc1986** [comment]
can I see your dependencies block in your build.gradle?

**Comment by yolapop** [comment]
Here I didn't change a single bit

    dependencies {
        compile 'com.android.support:appcompat-v7:21.+'
        compile 'com.xgc1986.parallaxPagerTransformer:library:1.0.0:sources'
    }

Maybe it has something to do with your cache? Just a guess

**Comment by xgc1986** [comment]
I thought the same, and I cleaned and still working, also I asked to some friends to try to add the dependency, and also is working for them.

**Comment by xgc1986** [comment]
But I am changing some things on build.gradle, to make it better, I hope then it works to you

**Comment by yolapop** [comment]
Yes maybe something's wrong on my computer. On the other hand, as I
learned, people say that jcenter is supposed to be the superset of maven
central so ideally it has to work without you moving to bintray. But
unfortunately it hadn't worked for me so I wrote this issue so if you want
you can revert commit to the state before I submit this issue.

Sorry for trouble.

**Comment by xgc1986** [comment]
try this, hope it works for you

 compile 'com.xgc1986.android:parallaxpagertransformer:1.0.0'

**Comment by yolapop** [comment]
Yep it works.. thank you =)
