### ISSUE TITLE
android:allowBackup conflict

### ISSUE THREAD

**Issue by RafaGonP** [xgc1986/ParallaxPagerTransformer#6]
Good morning:

Seems like you guys have in the library manifest, in the application tag, the android:allowBackup set on true.

This raises conflict when i try to put in my own manifest the android:allowBackup to false, and the "tools:replace" feature seems like doesn't work in allowBackup, there's even an issue raised in code.google.com.

A solution: remove in your manifest the android:allowBackup.

Thanks.

**Comment by xgc1986** [comment]
Done
